# Generated by Django 3.1.4 on 2020-12-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lessons',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
